# Generated by Django 3.0.7 on 2020-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('attempted_count', models.PositiveIntegerField(default=0)),
                ('min_age', models.SmallIntegerField(default=0)),
                ('max_age', models.SmallIntegerField(default=0)),
                ('min_income', models.SmallIntegerField(default=0)),
                ('max_income', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('optional', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('MCSO', 'Multi Choice Single Option'), ('MCMO', 'Multi Choice Multi Option'), ('OWNI', 'One Word or Number Input'), ('S', 'Scale input (1-5)'), ('E', 'Emoticon Input')], default='OWNI', max_length=4)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('age', models.PositiveIntegerField()),
                ('income', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('attempted_polls', models.ManyToManyField(blank=True, related_name='users_attempted', to='polls.Poll')),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=200)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.Poll')),
                ('poll_taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='polls.Question')),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id'], name='polls_userp_id_f90537_idx'),
        ),
    ]
