# Generated by Django 3.0.7 on 2020-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200622_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='poll',
            field=models.ManyToManyField(related_name='responses', to='polls.Poll'),
        ),
    ]
