# Generated by Django 3.0.7 on 2020-06-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200618_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MCSO', 'Multi Choice Single Option'), ('MCMO', 'Multi Choice Multi Option'), ('OWNI', 'One Word or Number Input'), ('S', 'Scale input (1-5)'), ('E', 'Emoticon Input')], default='MCMO', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
