# Generated by Django 3.0.7 on 2020-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200620_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
