# Generated by Django 3.0.7 on 2020-06-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200620_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MCSO', 'Multi Choice Single Option'), ('MCMO', 'Multi Choice Multi Option'), ('OWNI', 'One Word or Number Input'), ('S', 'Scale input (1-5)'), ('E', 'Emoticon Input')], default='OWNI', max_length=4),
        ),
    ]
