# Generated by Django 3.0.7 on 2020-06-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
